/********************************************************************
* enCalDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error enCalDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableenCalDict();
extern void G__cpp_setup_inheritanceenCalDict();
extern void G__cpp_setup_typetableenCalDict();
extern void G__cpp_setup_memvarenCalDict();
extern void G__cpp_setup_globalenCalDict();
extern void G__cpp_setup_memfuncenCalDict();
extern void G__cpp_setup_funcenCalDict();
extern void G__set_cpp_environmentenCalDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TSlsDetector.h"
#include "enCalWizard.h"
#include "enCalLogClass.h"
#include "fileIOStatic.h"
#include "energyCalibration.h"
#include "energyConversion.h"
#include "sls_detector_defs.h"
#include "scanStep.h"
#include "angularConversionStatic.h"
#include "angCalLogClass.h"
#include "angularCalibration.h"
#include "angCalWizard.h"
#include "badChannelCorrections.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__enCalDictLN_TClass;
extern G__linked_taginfo G__enCalDictLN_TBuffer;
extern G__linked_taginfo G__enCalDictLN_TMemberInspector;
extern G__linked_taginfo G__enCalDictLN_TObject;
extern G__linked_taginfo G__enCalDictLN_string;
extern G__linked_taginfo G__enCalDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__enCalDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__enCalDictLN_TList;
extern G__linked_taginfo G__enCalDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__enCalDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__enCalDictLN_TH1F;
extern G__linked_taginfo G__enCalDictLN_TH2F;
extern G__linked_taginfo G__enCalDictLN_TGraphErrors;
extern G__linked_taginfo G__enCalDictLN_angleConversionConstant;
extern G__linked_taginfo G__enCalDictLN_TGObject;
extern G__linked_taginfo G__enCalDictLN_TQObject;
extern G__linked_taginfo G__enCalDictLN_TGWindow;
extern G__linked_taginfo G__enCalDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__enCalDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__enCalDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__enCalDictLN_TGFrame;
extern G__linked_taginfo G__enCalDictLN_TGCompositeFrame;
extern G__linked_taginfo G__enCalDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__enCalDictLN_TGTextButton;
extern G__linked_taginfo G__enCalDictLN_TGVerticalFrame;
extern G__linked_taginfo G__enCalDictLN_TGHorizontalFrame;
extern G__linked_taginfo G__enCalDictLN_TGMainFrame;
extern G__linked_taginfo G__enCalDictLN_TGGroupFrame;
extern G__linked_taginfo G__enCalDictLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__enCalDictLN_TGButtonGroup;
extern G__linked_taginfo G__enCalDictLN_TGTextEntry;
extern G__linked_taginfo G__enCalDictLN_TGLabel;
extern G__linked_taginfo G__enCalDictLN_TGNumberEntry;
extern G__linked_taginfo G__enCalDictLN_TGComboBox;
extern G__linked_taginfo G__enCalDictLN_TGCheckButton;
extern G__linked_taginfo G__enCalDictLN_THStack;
extern G__linked_taginfo G__enCalDictLN_energyCalibration;
extern G__linked_taginfo G__enCalDictLN_enCalWizard;
extern G__linked_taginfo G__enCalDictLN_scanStep;
extern G__linked_taginfo G__enCalDictLN_angularCalibration;
extern G__linked_taginfo G__enCalDictLN_fitStep;
extern G__linked_taginfo G__enCalDictLN_angCalWizard;

/* STUB derived class for protected member access */
